apiVersion: v1
appVersion: "0.0.1"
description: A Helm chart for rutgers-vdc
name: rutgers-vdc
version: 0.0.1
dependencies:
- name: redis
  version: 10.5.7
  repository: https://charts.helm.sh/stable
  condition: redis.enabled
- name: mariadb
  version: 7.3.14
  repository: https://charts.helm.sh/stable
  condition: mariadb.enabled
