image: registry.gitlab.com/notch8/scripts/builder:latest
services:
  - name: docker:dind
  - name: redis:3
  - name: postgres
  - name: registry.gitlab.com/notch8/rutgers-vdc/solr:latest
    entrypoint: ["docker-entrypoint.sh", "solr-precreate", "hyrax", "/builds/notch8/rutgers-vdc/solr/config"]
  - name: botimer/fcrepo:4.5.1
stages:
  - build
  - test
#  - review
#  - staging
#  - production

variables:
  DOCKER_DRIVER: overlay
  REGISTRY_HOST: registry.gitlab.com
  REGISTRY_URI: /notch8/rutgers-vdc
  FEDORA_URL: http://botimer-fcrepo:8080/fcrepo/rest
  SOLR_URL: http://solr:8983/solr/hyrax
  REDIS_HOST: redis

before_script:
  - export TAG=${CI_COMMIT_SHA:0:8}
  - export BRANCH=${CI_COMMIT_REF_NAME}
  - export REGISTRY_HOST=${CI_REGISTRY}
  - export REGISTRY_URI="/${CI_PROJECT_PATH}"

solr_build:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - sc build -s solr
    - sc push -s solr
  when: manual

build:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - sc build
    - sc push
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  tags:
    - docker

rspec:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  script:
    - cd /data
    - bundle exec rspec
  tags:
    - docker
