version: '2.2'

services:
  main:
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG}"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.development
    volumes:
      - .:/home/app/webapp:delegated

  web:
    extends: main
    environment:
      VIRTUAL_HOST: vdc.docker
      VIRTUAL_PORT: 80
      IN_DOCKER: 'true'
      HUB_URL: "http://chrome:4444/wd/hub"
    ports:
      - "${DEV_PORT}"
      - "3010:3010"
    depends_on:
      - redis
      - solr
      - fcrepo
      - mysql
      - worker
      - chrome

  worker:
    extends: main
    command: bundle exec sidekiq
    depends_on:
      - redis
      - solr
      - fcrepo
      - mysql

  redis:
    image: redis:3
    ports:
      - '6379'
    volumes:
      - 'redis:/data'

  mysql:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - 'mysql:/var/lib/mysql'

  solr:
    image: registry.gitlab.com/notch8/rutgers-vdc/solr:latest
    build:
      context: .
      dockerfile: Dockerfile.solr
    ports:
      - "8983"
    volumes:
      - './solr/config:/opt/config'
    command:
      - sh
      - -c
      - "precreate-core hyrax_test /opt/config; solr-precreate hyrax /opt/config"


  fcrepo:
    image: botimer/fcrepo:4.5.1
    volumes:
      - 'fcrepo:/opt/data'
    ports:
      - "8984:8080"

  chrome:
    image: selenium/standalone-chrome-debug:3.141.59-20201010
    logging:
      driver: none
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2G
    ports:
      - "4444:4444"
      - "5959:5900"

volumes:
  fcrepo:
  mysql:
  redis:
