version: '2.2'
services:
  main:
    build: .
    image: registry.gitlab.com/notch8/rutgers-vdc
    env_file:
      - .env.development
      - .env
    volumes:
      - .:/data

  web:
    extends: main
    command: bin/rails server --port 3000 --binding 0.0.0.0
    environment:
      VIRTUAL_HOST: vdc.docker
      VIRTUAL_PORT: 3000
    ports:
      - "${DEV_PORT}"
    depends_on:
      - redis
      - solr
      - fcrepo
      - mysql

  redis:
    image: redis:3
    ports:
      - '6379'
    volumes:
      - 'redis:/data'

  mysql:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - 'mysql:/var/lib/mysql'

  solr:
    image: registry.gitlab.com/notch8/rutgers-vdc/solr:latest
    build:
      context: .
      dockerfile: Dockerfile.solr
    ports:
      - "8983:8983"
    volumes:
      - './solr/config:/opt/config'
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - hyrax
      - /opt/config

  fcrepo:
    image: botimer/fcrepo:4.5.1
    volumes:
      - 'fcrepo:/opt/data'
    ports:
      - "8984:8080"

volumes:
  fcrepo:
  mysql:
  redis:
