---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fcrepo.name" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: fcrepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
      component: fcrepo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
        component: fcrepo
    spec:
      restartPolicy: Always
      {{- if .Values.fcrepo.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.fcrepo.imagePullSecrets }}
      {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "app.fcrepo.name" . }}
      initContainers:
        - name: "remove-lost-found"
          image: "busybox:1.25.0"
          command:
            - rm
            - -fr
            - /fcrepo4-data/lost+found
          volumeMounts:
            - name: data
              mountPath: /fcrepo4-data
      containers:
        - name: fcrepo
          image: {{ .Values.fcrepo.image.repository }}:{{ .Values.fcrepo.image.tag }}
          livenessProbe:
            tcpSocket:
              port: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
          volumeMounts:
            - name: data
              mountPath: /fcrepo4-data
          envFrom:
            - configMapRef:
                name: {{ template "app.fcrepo-env.name" . }}
            - secretRef:
                name: {{ template "app.fcrepo-env.name" . }}
