---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.solr.name" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: solr
spec:
  ports:
    - protocol: TCP
      port: 8983
  selector:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
    component: solr
