---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.solr.name" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: solr 
spec:
  replicas: {{ .Values.solr.replicas }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
      component: solr
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
        component: solr
    spec:
      restartPolicy: Always
      {{- if .Values.solr.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.solr.imagePullSecrets }}
      {{- end }}
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: {{ template "app.rails-env.name" . }}-shared
        - name: solr-home
          persistentVolumeClaim:
            claimName: {{ template "app.solr.name" . }}-home
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chown -R 8983:8983 /opt/solr/server/solr/mycores"]
          volumeMounts:
            - mountPath: /solr_home 
              name: shared
              subPath: solr
            - mountPath: /opt/solr/server/solr/mycores
              name: solr-home
      containers:
        - name: solr
          image: {{ .Values.solr.image.repository }}:{{ .Values.solr.image.tag }}
          imagePullPolicy: IfNotPresent
          command: 
            - sh
            - -c
            - "precreate-core hyrax_test /opt/config; solr-precreate hyrax /opt/config"
          # Use sub-path for individual folders
          volumeMounts:
            - mountPath: /solr_home 
              name: shared
              subPath: solr
            - mountPath: /opt/solr/server/solr/mycores
              name: solr-home
          readinessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 60
            periodSeconds: 120