terms:
  - id: 1
    term: Department of Agriculture (USDA)
    active: true
  - id: 2
    term: Department of Defense (DOD)
    active: true
  - id: 3
    term: Department of Education
    active: true
  - id: 4
    term: Department of Energy
    active: true
  - id: 5
    term: Environmental Protection Agency (EPA)
    active: true
  - id: 6
    term: Institute of Museum and Library Services (IMLS)
    active: true
  - id: 7
    term: Mellon Foundation
    active: true
  - id: 8
    term: National Aeronautics and Space Agency (NASA)
    active: true
  - id: 9
    term: National Endowment for the Arts (NEA)
    active: true
  - id: 10
    term: National Endowment for the Humanities (NEH)
    active: true
  - id: 11
    term: National Institutes of Health (NIH)
    active: true
  - id: 12
    term: National Oceanographic and Atmospheric Administration (NOAA)
    active: true
  - id: 13
    term: National Science Foundation (NSF)
    active: true
