terms:
    - id: isReferencedBy
      term: isReferencedBy
      active: true
    - id: isAnalysisOf
      term: isAnalysisOf
      active: true
    - id: isAccessedBy
      term: isAccessedBy
      active: true
