development:
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST'] || ENV['REDIS_DEV_HOST'] || 'localhost' %>:6379

test:
  adapter: async

production:
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST'] || 'localhost' %>:6379/1
  channel_prefix: ccql_production
