default: &default
  adapter:  <%= ENV['DB_ADAPTER'] %>
  host:     <%= ENV['MYSQL_HOST'] %>
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  database: <%= ENV['MYSQL_DATABASE'] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['TEST_DB'] %>

staging:
  <<: *default
