development:
  archivist:
    - archivist1@example.com
  admin:
    - admin@example.com

test:
  archivist:
    - archivist1@example.com
  admin:
    - admin@example.com

production:
  archivist:
    - archivist1@example.com
  admin:
    - rob@notch8.com
