development:
  archivist:
    - archivist1@example.com
  admin:
    - admin@example.com
    - rjantz@libraries.rutgers.edu
    - gagnew@rutgers.edu
    - rob@notch8.com

test:
  archivist:
    - archivist1@example.com
  admin:
    - admin@example.com

production:
  archivist:
    - archivist1@example.com
  admin:
    - rob@notch8.com
    - rjantz@libraries.rutgers.edu
    - gagnew@rutgers.edu
